version: '3.7'

services:
  webbanhang:
    container_name: webbanhang
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
    build:
      context: ./WebBanHang
      dockerfile: Dockerfile
    depends_on:
      - db_webbanhang
    ports:
      - 5000:5000
    networks:
      - network_metyl
  shop-rest-admin:
    container_name: shop-rest-admin
    build:
      context: ./shop-rest-admin
      dockerfile: Dockerfile
    depends_on:
      - webbanhang
    ports:
      - 8080:80
    networks:
      - network_metyl
  nextjs-metyl:
    container_name: nextjs-metyl
    build:
      context: ./nextjs-metyl
      dockerfile: Dockerfile
    depends_on:
      - webbanhang
    ports:
      - 3000:3000
    networks:
      - network_metyl
  db_webbanhang:
    container_name: db_webbanhang
    build:
      context: .
      dockerfile: .docker/Dockerfile
    ports:
      - 1433:1433
    networks:
      - network_metyl
    volumes:
      - sqldata:/var/lib/sqlserver/data
networks:
  network_metyl:
    driver: bridge
volumes:
  sqldata: